---
- name: Is run_validations defined
  when: run_validations is defined
  fail:
    msg: |
      run_validation is deprecated. Please remove this parameter

- name: Is enable_metrics defined
  when: enable_metrics is defined
  fail:
    msg: |
      enable_metrics is deprecated. Please remove this parameter

- name: Is centos_mirror defined
  when: centos_mirror is defined
  fail:
    msg: |
      centos_mirror is deprecated. Please remove this parameter

- name: Is mirror_base_directory defined
  when: mirror_base_directory is defined
  fail:
    msg: |
      mirror_base_directory is deprecated. Please remove this parameter

- name: Is manage_mirror_device defined
  when: manage_mirror_device is defined
  fail:
    msg: |
      manage_mirror_device is deprecated. Please remove this parameter

- name: Is centos_mirror_device defined
  when: centos_mirror_device is defined
  fail:
    msg: |
      centos_mirror_device is deprecated. Please remove this parameter

- name: Is no_proxy defined
  when: no_proxy is defined
  fail:
    msg: |
      no_proxy is deprecated. Please remove this parameter
