---
- name: common tags for metrics
  tags:
    - metrics
  when:
    - enable_metrics|bool
  block:
    - name: add new repository for latest podman
      yum_repository:
        baseurl: 'https://buildlogs.centos.org/centos/7/virt/$basearch/container/'
        description: 'Latest podman binaries'
        enabled: true
        gpgcheck: false
        name: centos7-virt-container
        skip_if_unavailable: true

    - name: install podman
      package:
        name: podman
        state: latest

    - name: create host directories for persistent data
      file:
        path: "/var/lib/containers/storage/mounts/{{ item }}"
        state: directory
        setype: svirt_sandbox_file_t
      with_items:
        - graphite
        - graphite/conf
        - graphite/storage
    - name: grafana directories
      file:
        path: "/var/lib/containers/storage/mounts/{{ item }}"
        state: directory
        setype: svirt_sandbox_file_t
        mode: 0777

      with_items:
        - grafana
        - grafana/data

    - name: create graphite container
      import_role:
        name: podman
        tasks_from: run_container
      vars:
        ct_name: graphite
        image: graphiteapp/graphite-statsd
        volumes:
          - '-v /var/lib/containers/storage/mounts/graphite/conf:/opt/graphite/conf'
          - '-v /var/lib/containers/storage/mounts/graphite/storage:/opt/graphite/storage'
        ports:
          - '-p 8080:80'
          - '-p 2003-2004:2003-2004'
          - '-p 2023-2024:2023-2024'
          - '-p 8125:8125/udp'
          - '-p 8126:8126'

    - name: create grafana container
      import_role:
        name: podman
        tasks_from: run_container
      vars:
        ct_name: grafana
        image: grafana/grafana
        ports:
          - '-p 3000:3000'
        volumes:
          - '-v /var/lib/containers/storage/mounts/grafana/data:/var/lib/grafana'
