---
parameter_defaults:
  NeutronMechanismDrivers: ovn
  ContainerImagePrepare:
  - set:
      name_prefix: {{ container_name_prefix }}
      namespace: {{ container_namespace }}
      tag: {{ container_tag }}


