enable_metrics: no
overclouds: 1
vms:
  - name: undercloud
    cpu: 4
    memory: 16384
    interfaces:
      - mac: "24:42:53:21:52:15"
        network: default
      - mac: "24:42:53:21:52:16"
    autostart: yes
  - name: controller-0
    cpu: 2
    memory: 4096
    interfaces:
      - mac: "24:42:53:21:52:25"
      - mac: "24:42:53:21:52:26"
    autostart: no
  - name: controller-1
    cpu: 2
    memory: 4096
    interfaces:
      - mac: "24:42:53:21:52:35"
      - mac: "24:42:53:21:52:36"
    autostart: no
  - name: controller-2
    cpu: 2
    memory: 4096
    interfaces:
      - mac: "24:42:53:21:52:45"
      - mac: "24:42:53:21:52:46"
    autostart: no
  - name: compute-0
    cpu: 2
    memory: 4096
    interfaces:
      - mac: "24:42:53:21:52:55"
      - mac: "24:42:53:21:52:56"
    autostart: no
  - name: compute-1
    cpu: 2
    memory: 4096
    interfaces:
      - mac: "24:42:53:21:52:65"
      - mac: "24:42:53:21:52:66"
    autostart: no
  - name: ceph-0
    cpu: 2
    memory: 8192
    interfaces:
      - mac: "24:42:53:21:52:75"
      - mac: "24:42:53:21:52:76"
    autostart: no
  - name: ceph-1
    cpu: 2
    memory: 8192
    interfaces:
      - mac: "24:42:53:21:52:85"
      - mac: "24:42:53:21:52:86"
    autostart: no
  - name: ceph-2
    cpu: 2
    memory: 8192
    interfaces:
      - mac: "24:42:53:21:52:95"
      - mac: "24:42:53:21:52:96"
    autostart: no

virt_user: virtuser
basedir: "/home/{{virt_user}}"
undercloud_password: fooBar
centos_mirror: no
manage_mirror_device: yes
mirror_base_directory: /srv/mirror
centos_mirror_device: /dev/sdc
base_image: centos
vm_prefix: lab
root_device: 1
growfs_part: /dev/sda1
guestfs_appliance: "appliance-1.38.0.tar.xz"
python_interpreter: /usr/bin/python
undercloud_hostname: undercloud.localdomain
num_osds: 1
