---
- name: Fetch latest delorean repository
  get_url:
    url: "https://trunk.rdoproject.org/centos8/{{ tripleo_mod }}/delorean.repo"
    dest: /etc/yum.repos.d/delorean.repo

- name: Fetch latest delorean-deps repository
  get_url:
    url: "https://trunk.rdoproject.org/centos8/delorean-deps.repo"
    dest: /etc/yum.repos.d/delorean-deps.repo

- name: Inject ceph-storage repository
  yum_repository:
    name: storage8-ceph-nautilus
    description: storage8-ceph-nautilus
    baseurl: https://trunk.rdoproject.org/centos8/deps/storage/storage8-ceph-nautilus/x86_64/
    gpgcheck: false

- name: Drop ghost ens3 interface
  file:
    path: /etc/sysconfig/network-scripts/ifcfg-ens3
    state: absent
