---
- name: tagging
  tags:
    - deploy-ci
  block:
    - name: install pip
      package:
        name: python-pip
    - name: install rdopkg
      command: pip install rdopkg
- name: common tags
  tags:
    - deploy-ci
  become: yes
  become_user: stack
  when: ci_tools|bool
  block:
    - name: clone tripleo-ci in stack home
      git:
        accept_hostkey: yes
        dest: "/home/stack/tripleo-ci"
        repo: "https://git.openstack.org/openstack-infra/tripleo-ci"

    - name: install tripleo-ci dependencies
      shell: |
        TRIPLEO_ROOT=/home/stack
        /home/stack/tripleo-ci/scripts/tripleo.sh --delorean-setup > /home/stack/deploy-ci.log
      args:
        creates: /home/stack/tripleo/delorean
