---
- name: set hostname properly
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 undercloud.{{ansible_domain}} undercloud localhost localhost.localdomain"
    regexp: '^127\.0\.0\.1'

- name: fetch latest repo version
  shell: |
    curl -s https://trunk.rdoproject.org/centos7/current/ | awk '/python2-tripleo-repos/ { print $6}' | cut -d '"' -f 2
  register: auto_tripleo_repo_version
- name: install tripleo repository
  yum:
    name: "https://trunk.rdoproject.org/centos7/current/{{tripleo_repo_version.stdout}}"
    state: present

- name: enable tripleo_version repository
  command: tripleo-repos -b "{{tripleo_version}}" current
  args:
    creates: "/etc/yum.repos.d/delorean-{{tripleo_version}}.repo"

- name: install some tools
  yum:
    name: "{{item}}"
    state: present
  loop:
    - git
    - tmux
    - vim

- name: do we have a swap file
  stat:
    path: /dev/sdb
  register: swap_on

- name: set fstab entry for swap if needed
  lineinfile:
    backup: yes
    dest: /etc/fstab
    line: '/dev/sdb swap swap defaults 0 0'
  when:
    - swap_on.stat.exists
    - swap_on.stat.isblk

- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: present
