---
- name: Create metalsmith config yaml
  template:
    src: metalsmith.yaml.j2
    dest: "/home/stack/metalsmith-{{ item }}.yaml"
  loop: "{{ range(0, overclouds)|list }}"

- name: Provision nodes
  include_role:
    name: tripleo.operator.tripleo_overcloud_node_provision
  vars:
    tripleo_overcloud_node_provision_output_file: "overcloud-baremetal-deployed-{{ item }}.yaml"
    tripleo_overcloud_node_provision_stack: "overcloud-{{ item }}"
    tripleo_overcloud_node_provision_deployment_file: "~/metalsmith-{{ item }}.yaml"
  loop: "{{ range(0, overclouds)|list }}"
