---
- name: Some hacks specificy for RHEL
  when: base_image == 'rhel'
  block:
    - name: "unmanage {{ unmanage_iface }}"
      command: nmcli dev set {{ unmanage_iface }} managed no

    - name: ensure we do have DNS resolution
      copy:
        dest: /etc/resolv.conf
        content: |
          {% for nameserver in nameservers %}
          nameserver {{ nameserver }}
          {% endfor %}

    - name: install some packages
      package:
        name:
          - iptables-services
          - network-scripts
          - lvm2
          - libvirt-client

    - name: some hiera override
      copy:
        dest: /home/stack/undercloud_hiera.yaml
        content: |
          glance_backend: 'file'
          tripleo::profile::base::nova::enable_cache: false
        owner: stack
        group: stack

    - name: install custom CA if provided
      when: custom_ca != ''
      block:
        - name: fetch CA via proxy
          when: proxy_host is defined
          environment:
            - http_proxy: "http://{{ proxy_host }}"
            - https_proxy: "http://{{ proxy_host }}"
          get_url:
            url: "{{ custom_ca }}"
            dest: /etc/pki/ca-trust/source/anchors/custom-ssl-ca.crt
            validate_certs: no

        - name: fetch CA without proxy
          when: proxy_host is not defined
          get_url:
            url: "{{ custom_ca }}"
            dest: /etc/pki/ca-trust/source/anchors/custom-ssl-ca.crt
            validate_certs: no

        - name: install custom CA
          command: update-ca-trust
