---
- name: set up rhos if needed
  when:
    - base_image == 'rhel'
  block:
    - name: check for rhos-release repo file
      stat:
        path: /etc/yum.repos.d/rhos-release.repo
      register: local_rhos_release_repo

    - block:
        - name: add rhos-release repository
          yum_repository:
            name: rhos-release
            description: RHOS Release
            baseurl: "{{ rhos_release_repo_url }}"
            gpgcheck: no
        - name: yum-clean-metadata
          command: yum clean metadata
          args:
            warn: no
      when: not local_rhos_release_repo.stat.exists

    - name: ensure rhos-release is latest
      package:
        name: rhos-release
        state: latest

    - name: run rhos-release
      command: rhos-release {{ rhos_release_opts|default('') }} {{ rhos_release_version }}
      become: true

