- name: create stack user
  user:
    comment: "Stack user for tripleo"
    create_home: yes
    generate_ssh_key: yes
    name: stack
    shell: "/bin/bash"
    ssh_key_bits: 4096
    state: present

- name: create ansible temp dir for stack user
  file:
    path: /home/stack/.ansible/tmp
    state: directory
    group: stack
    mode: 0700
    owner: stack

- name: create root keypair
  user:
    generate_ssh_key: yes
    name: root
    shell: "/bin/bash"
    ssh_key_bits: 4096
    state: present

- name: give sudo accesses
  tags:
    - sudo
  copy:
    dest: /etc/sudoers.d/stack
    src: stack.sudoers
    group: root
    mode: '0440'
    owner: root

- name: copy root authorized_keys to stack user
  copy:
    dest: /home/stack/.ssh/authorized_keys
    group: stack
    mode: '0644'
    owner: stack
    remote_src: yes
    src: /root/.ssh/authorized_keys

- name: get stack pub key
  slurp:
    src: /home/stack/.ssh/id_rsa.pub
  register: stack_pubkey

- name: get root pub key
  slurp:
    src: /root/.ssh/id_rsa.pub
  register: root_pubkey

- name: authorize stack user on root via ssh
  authorized_key:
    user: root
    key: "{{ stack_pubkey['content'] |b64decode }}"

- name: authorize stack user on stack with ssh
  authorized_key:
    user: stack
    key: "{{ stack_pubkey['content'] |b64decode }}"

- name: authorize root user on stack via ssh
  authorized_key:
    user: stack
    key: "{{ root_pubkey['content'] |b64decode }}"

- name: authorize root user on root via ssh
  authorized_key:
    user: root
    key: "{{ root_pubkey['content'] |b64decode }}"

- name: ensure free access to the overcloud nodes
  copy:
    dest: /home/stack/.ssh/config
    src: ssh_config
    owner: stack
    group: stack
    mode: 0640

- name: copy env-cleanup script to stack hope
  copy:
    dest: /home/stack/env-cleanup.sh
    src: env-cleanup.sh
    group: root
    mode: 0755
    owner: root
