virt_user: virtuser
tripleo_version: rocky
overcloud_images:
  - file: ironic-python-agent.tar
    content: ironic-python-agent.kernel
  - file: overcloud-full.tar
    content: overcloud-full.qcow2
use_heat: no
ci_tools: yes
deploy_undercloud: yes
deploy_overcloud: no
undercloud_sample: /usr/share/python-tripleoclient/undercloud.conf.sample
undercloud_dns: 192.168.122.1
patches: []
custom_rpms: []
standalone: no
standalone_ceph: no
containerized_undercloud: yes
synchronize: []
synchronize_default_dest: /home/stack/tripleo/
ceph_version: luminous
tmate_release: 2.2.1
semodules: []
overcloud_container_cli: docker
overcloud_image_update: yes
