virt_user: virtuser
tripleo_version: rocky
overcloud_images:
  - file: ironic-python-agent.tar
    content: ironic-python-agent.kernel
  - file: overcloud-full.tar
    content: overcloud-full.qcow2
use_heat: no
ci_tools: yes
deploy_undercloud: yes
deploy_overcloud: no
undercloud_sample: /usr/share/python-tripleoclient/undercloud.conf.sample
undercloud_dns: 192.168.122.1
patches: []
custom_rpms: []
standalone: no
standalone_ceph: no
containerized_undercloud: yes
synchronize: []
synchronize_default_dest: /home/stack/tripleo/
ceph_version: luminous
tmate_release: 2.2.1
semodules: []
overcloud_container_cli: podman
overcloud_image_update: yes
undercloud_low_memory: no
disable_selinux: no
additional_envs: []
container_registry_ip: ''
ceph_container_namespace: 'docker.io/ceph'
ceph_container_tag: 'v3.2.0-stable-3.2-luminous-centos-7-x86_64'
container_name_prefix: 'centos-binary'
container_name_suffix: "''"
container_namespace: 'docker.io/tripleomaster'
container_tag: current-tripleo
no_proxy: "localhost,127.0.0.1,192.168.24.0,192.168.24.1,192.168.24.2,192.168.24.3,192.168.24.4,192.168.24.5,192.168.24.6,192.168.24.7,192.168.24.8,192.168.24.9,192.168.24.10,192.168.24.11,192.168.24.12,192.168.24.13,192.168.24.14,192.168.24.15,192.168.24.16,192.168.24.17,192.168.24.18,192.168.24.19,192.168.24.20,192.168.24.21,192.168.24.22,192.168.24.23,192.168.24.24"
custom_repositories: []
tripleoclient_pkgname: python-tripleoclient
unmanage_iface: ens3
local_registry: 192.168.24.2:8787
custom_ca: ''
nameservers:
  - 1.1.1.1
  - 8.8.8.8
undercloud_config: []
